"""empty message

Revision ID: 05262dd0be9d
Revises: 9f83a940bd0b
Create Date: 2020-01-14 01:03:25.907365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05262dd0be9d'
down_revision = '9f83a940bd0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_post_author_fkey', 'post', type_='foreignkey')
    op.drop_column('post', 'post_author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('post_post_author_fkey', 'post', 'user', ['post_author'], ['id'])
    # ### end Alembic commands ###
