"""empty message

Revision ID: 05b71a15baf3
Revises: 836de3a49408
Create Date: 2020-01-15 03:27:49.146269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b71a15baf3'
down_revision = '836de3a49408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('post_id', sa.String(), nullable=True))
    op.drop_constraint('comment_commented_on_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['post_id'])
    op.drop_column('comment', 'commented_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('commented_on', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_commented_on_fkey', 'comment', 'post', ['commented_on'], ['post_id'])
    op.drop_column('comment', 'post_id')
    # ### end Alembic commands ###
