"""empty message

Revision ID: 0d716f8c431c
Revises: a2dfb0aea042
Create Date: 2020-01-14 01:11:07.321835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d716f8c431c'
down_revision = 'a2dfb0aea042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_post_author_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['post_author'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_post_author_fkey', 'post', 'user', ['post_author'], ['public_id'])
    # ### end Alembic commands ###
