"""empty message

Revision ID: 14771996a7d0
Revises: 0d716f8c431c
Create Date: 2020-01-14 02:04:18.558971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14771996a7d0'
down_revision = '0d716f8c431c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('pet_owner', sa.String(), nullable=True))
    op.create_foreign_key(None, 'pet', 'user', ['pet_owner'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pet', type_='foreignkey')
    op.drop_column('pet', 'pet_owner')
    # ### end Alembic commands ###
