"""empty message

Revision ID: 1800bb09874d
Revises: e41b8a329b47
Create Date: 2020-01-20 00:31:34.733191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1800bb09874d'
down_revision = 'e41b8a329b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_post_author_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['post_author'], ['username'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_post_author_fkey', 'post', 'user', ['post_author'], ['public_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
