"""empty message

Revision ID: 2cdfe426da14
Revises: 23de523210ab
Create Date: 2020-01-13 23:40:14.588487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cdfe426da14'
down_revision = '23de523210ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'user', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'author')
    # ### end Alembic commands ###
