"""empty message

Revision ID: 3efce2439644
Revises: 1800bb09874d
Create Date: 2020-01-20 01:57:34.678939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3efce2439644'
down_revision = '1800bb09874d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_posted_by_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['posted_by'], ['username'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_posted_by_fkey', 'comment', 'user', ['posted_by'], ['public_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
