"""empty message

Revision ID: 541fb32e9da1
Revises: 
Create Date: 2020-01-20 04:50:04.650065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541fb32e9da1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('req_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=True),
    sa.Column('requester_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.public_id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['requester_id'], ['user.public_id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('user_request_rel',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('req_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['req_id'], ['request.public_id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.public_id'], ondelete='cascade')
    )
    op.add_column('deal', sa.Column('req_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'deal', 'request', ['req_id'], ['public_id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deal', type_='foreignkey')
    op.drop_column('deal', 'req_id')
    op.drop_table('user_request_rel')
    op.drop_table('request')
    # ### end Alembic commands ###
