"""empty message

Revision ID: 6efb28dbebdd
Revises: ab2534ba69b3
Create Date: 2020-01-18 14:49:31.048131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6efb28dbebdd'
down_revision = 'ab2534ba69b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_post_id_fkey', 'comment', type_='foreignkey')
    op.drop_constraint('comment_posted_by_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['public_id'], ondelete='cascade')
    op.create_foreign_key(None, 'comment', 'user', ['posted_by'], ['username'], ondelete='cascade')
    op.drop_constraint('deal_deal_owner_fkey', 'deal', type_='foreignkey')
    op.create_foreign_key(None, 'deal', 'user', ['deal_owner'], ['username'], ondelete='cascade')
    op.drop_constraint('pet_pet_owner_fkey', 'pet', type_='foreignkey')
    op.create_foreign_key(None, 'pet', 'user', ['pet_owner'], ['username'], ondelete='cascade')
    op.drop_constraint('post_post_author_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['post_author'], ['username'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_post_author_fkey', 'post', 'user', ['post_author'], ['username'])
    op.drop_constraint(None, 'pet', type_='foreignkey')
    op.create_foreign_key('pet_pet_owner_fkey', 'pet', 'user', ['pet_owner'], ['username'])
    op.drop_constraint(None, 'deal', type_='foreignkey')
    op.create_foreign_key('deal_deal_owner_fkey', 'deal', 'user', ['deal_owner'], ['username'])
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_posted_by_fkey', 'comment', 'user', ['posted_by'], ['username'])
    op.create_foreign_key('comment_post_id_fkey', 'comment', 'post', ['post_id'], ['public_id'])
    # ### end Alembic commands ###
