"""empty message

Revision ID: 9f83a940bd0b
Revises: 2cdfe426da14
Create Date: 2020-01-14 00:00:01.335057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f83a940bd0b'
down_revision = '2cdfe426da14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_author', sa.Integer(), nullable=True))
    op.drop_constraint('post_author_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['post_author'], ['id'])
    op.drop_column('post', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_author_fkey', 'post', 'user', ['author'], ['id'])
    op.drop_column('post', 'post_author')
    # ### end Alembic commands ###
