"""empty message

Revision ID: a00b4ff2fd1f
Revises: c7618cfc9d9c
Create Date: 2020-01-11 15:02:43.318882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00b4ff2fd1f'
down_revision = 'c7618cfc9d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_price_rel',
    sa.Column('pet_id', sa.String(), nullable=True),
    sa.Column('deal_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.public_id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.public_id'], )
    )
    op.drop_table('pet_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_price',
    sa.Column('pet_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deal_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.public_id'], name='pet_price_deal_id_fkey'),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.public_id'], name='pet_price_pet_id_fkey')
    )
    op.drop_table('pet_price_rel')
    # ### end Alembic commands ###
