"""empty message

Revision ID: a2dfb0aea042
Revises: 05262dd0be9d
Create Date: 2020-01-14 01:08:31.154626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2dfb0aea042'
down_revision = '05262dd0be9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_author', sa.String(), nullable=True))
    op.create_foreign_key(None, 'post', 'user', ['post_author'], ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'post_author')
    # ### end Alembic commands ###
