"""empty message

Revision ID: c7618cfc9d9c
Revises: d94aa11223b1
Create Date: 2020-01-11 15:01:41.505346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7618cfc9d9c'
down_revision = 'd94aa11223b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_price',
    sa.Column('pet_id', sa.String(), nullable=True),
    sa.Column('deal_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.public_id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.public_id'], )
    )
    op.create_table('pet_sale_rel',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('trans_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trans_id'], ['deal.public_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.public_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet_sale_rel')
    op.drop_table('pet_price')
    # ### end Alembic commands ###
