"""empty message

Revision ID: c79ad0841767
Revises: 6efb28dbebdd
Create Date: 2020-01-18 14:56:20.932575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c79ad0841767'
down_revision = '6efb28dbebdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_post_rel_comm_id_fkey', 'comment_post_rel', type_='foreignkey')
    op.drop_constraint('comment_post_rel_post_id_fkey', 'comment_post_rel', type_='foreignkey')
    op.create_foreign_key(None, 'comment_post_rel', 'post', ['post_id'], ['public_id'], ondelete='cascade')
    op.create_foreign_key(None, 'comment_post_rel', 'comment', ['comm_id'], ['public_id'], ondelete='cascade')
    op.drop_constraint('pet_kind_rel_pet_id_fkey', 'pet_kind_rel', type_='foreignkey')
    op.drop_constraint('pet_kind_rel_specie_id_fkey', 'pet_kind_rel', type_='foreignkey')
    op.drop_constraint('pet_kind_rel_breed_id_fkey', 'pet_kind_rel', type_='foreignkey')
    op.create_foreign_key(None, 'pet_kind_rel', 'breed', ['breed_id'], ['public_id'], ondelete='cascade')
    op.create_foreign_key(None, 'pet_kind_rel', 'specie', ['specie_id'], ['public_id'], ondelete='cascade')
    op.create_foreign_key(None, 'pet_kind_rel', 'pet', ['pet_id'], ['public_id'], ondelete='cascade')
    op.drop_constraint('pet_price_rel_pet_id_fkey', 'pet_price_rel', type_='foreignkey')
    op.drop_constraint('pet_price_rel_deal_id_fkey', 'pet_price_rel', type_='foreignkey')
    op.create_foreign_key(None, 'pet_price_rel', 'deal', ['deal_id'], ['public_id'], ondelete='cascade')
    op.create_foreign_key(None, 'pet_price_rel', 'pet', ['pet_id'], ['public_id'], ondelete='cascade')
    op.drop_constraint('pet_sale_rel_trans_id_fkey', 'pet_sale_rel', type_='foreignkey')
    op.drop_constraint('pet_sale_rel_user_id_fkey', 'pet_sale_rel', type_='foreignkey')
    op.create_foreign_key(None, 'pet_sale_rel', 'user', ['user_id'], ['public_id'], ondelete='cascade')
    op.create_foreign_key(None, 'pet_sale_rel', 'deal', ['trans_id'], ['public_id'], ondelete='cascade')
    op.drop_constraint('user_business_rel_user_id_fkey', 'user_business_rel', type_='foreignkey')
    op.drop_constraint('user_business_rel_business_id_fkey', 'user_business_rel', type_='foreignkey')
    op.create_foreign_key(None, 'user_business_rel', 'business', ['business_id'], ['public_id'], ondelete='cascade')
    op.create_foreign_key(None, 'user_business_rel', 'user', ['user_id'], ['public_id'], ondelete='cascade')
    op.drop_constraint('user_circle_rel_circle_id_fkey', 'user_circle_rel', type_='foreignkey')
    op.drop_constraint('user_circle_rel_user_id_fkey', 'user_circle_rel', type_='foreignkey')
    op.create_foreign_key(None, 'user_circle_rel', 'user', ['user_id'], ['public_id'], ondelete='cascade')
    op.create_foreign_key(None, 'user_circle_rel', 'circle', ['circle_id'], ['public_id'], ondelete='cascade')
    op.drop_constraint('user_comment_rel_comm_id_fkey', 'user_comment_rel', type_='foreignkey')
    op.drop_constraint('user_comment_rel_user_id_fkey', 'user_comment_rel', type_='foreignkey')
    op.create_foreign_key(None, 'user_comment_rel', 'user', ['user_id'], ['public_id'], ondelete='cascade')
    op.create_foreign_key(None, 'user_comment_rel', 'comment', ['comm_id'], ['public_id'], ondelete='cascade')
    op.drop_constraint('user_pet_rel_pet_id_fkey', 'user_pet_rel', type_='foreignkey')
    op.drop_constraint('user_pet_rel_user_id_fkey', 'user_pet_rel', type_='foreignkey')
    op.create_foreign_key(None, 'user_pet_rel', 'user', ['user_id'], ['public_id'], ondelete='cascade')
    op.create_foreign_key(None, 'user_pet_rel', 'pet', ['pet_id'], ['public_id'], ondelete='cascade')
    op.drop_constraint('user_post_rel_public_id_fkey', 'user_post_rel', type_='foreignkey')
    op.drop_constraint('user_post_rel_user_id_fkey', 'user_post_rel', type_='foreignkey')
    op.create_foreign_key(None, 'user_post_rel', 'user', ['user_id'], ['public_id'], ondelete='cascade')
    op.create_foreign_key(None, 'user_post_rel', 'post', ['public_id'], ['public_id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_post_rel', type_='foreignkey')
    op.drop_constraint(None, 'user_post_rel', type_='foreignkey')
    op.create_foreign_key('user_post_rel_user_id_fkey', 'user_post_rel', 'user', ['user_id'], ['public_id'])
    op.create_foreign_key('user_post_rel_public_id_fkey', 'user_post_rel', 'post', ['public_id'], ['public_id'])
    op.drop_constraint(None, 'user_pet_rel', type_='foreignkey')
    op.drop_constraint(None, 'user_pet_rel', type_='foreignkey')
    op.create_foreign_key('user_pet_rel_user_id_fkey', 'user_pet_rel', 'user', ['user_id'], ['public_id'])
    op.create_foreign_key('user_pet_rel_pet_id_fkey', 'user_pet_rel', 'pet', ['pet_id'], ['public_id'])
    op.drop_constraint(None, 'user_comment_rel', type_='foreignkey')
    op.drop_constraint(None, 'user_comment_rel', type_='foreignkey')
    op.create_foreign_key('user_comment_rel_user_id_fkey', 'user_comment_rel', 'user', ['user_id'], ['public_id'])
    op.create_foreign_key('user_comment_rel_comm_id_fkey', 'user_comment_rel', 'comment', ['comm_id'], ['public_id'])
    op.drop_constraint(None, 'user_circle_rel', type_='foreignkey')
    op.drop_constraint(None, 'user_circle_rel', type_='foreignkey')
    op.create_foreign_key('user_circle_rel_user_id_fkey', 'user_circle_rel', 'user', ['user_id'], ['public_id'])
    op.create_foreign_key('user_circle_rel_circle_id_fkey', 'user_circle_rel', 'circle', ['circle_id'], ['public_id'])
    op.drop_constraint(None, 'user_business_rel', type_='foreignkey')
    op.drop_constraint(None, 'user_business_rel', type_='foreignkey')
    op.create_foreign_key('user_business_rel_business_id_fkey', 'user_business_rel', 'business', ['business_id'], ['public_id'])
    op.create_foreign_key('user_business_rel_user_id_fkey', 'user_business_rel', 'user', ['user_id'], ['public_id'])
    op.drop_constraint(None, 'pet_sale_rel', type_='foreignkey')
    op.drop_constraint(None, 'pet_sale_rel', type_='foreignkey')
    op.create_foreign_key('pet_sale_rel_user_id_fkey', 'pet_sale_rel', 'user', ['user_id'], ['public_id'])
    op.create_foreign_key('pet_sale_rel_trans_id_fkey', 'pet_sale_rel', 'deal', ['trans_id'], ['public_id'])
    op.drop_constraint(None, 'pet_price_rel', type_='foreignkey')
    op.drop_constraint(None, 'pet_price_rel', type_='foreignkey')
    op.create_foreign_key('pet_price_rel_deal_id_fkey', 'pet_price_rel', 'deal', ['deal_id'], ['public_id'])
    op.create_foreign_key('pet_price_rel_pet_id_fkey', 'pet_price_rel', 'pet', ['pet_id'], ['public_id'])
    op.drop_constraint(None, 'pet_kind_rel', type_='foreignkey')
    op.drop_constraint(None, 'pet_kind_rel', type_='foreignkey')
    op.drop_constraint(None, 'pet_kind_rel', type_='foreignkey')
    op.create_foreign_key('pet_kind_rel_breed_id_fkey', 'pet_kind_rel', 'breed', ['breed_id'], ['public_id'])
    op.create_foreign_key('pet_kind_rel_specie_id_fkey', 'pet_kind_rel', 'specie', ['specie_id'], ['public_id'])
    op.create_foreign_key('pet_kind_rel_pet_id_fkey', 'pet_kind_rel', 'pet', ['pet_id'], ['public_id'])
    op.drop_constraint(None, 'comment_post_rel', type_='foreignkey')
    op.drop_constraint(None, 'comment_post_rel', type_='foreignkey')
    op.create_foreign_key('comment_post_rel_post_id_fkey', 'comment_post_rel', 'post', ['post_id'], ['public_id'])
    op.create_foreign_key('comment_post_rel_comm_id_fkey', 'comment_post_rel', 'comment', ['comm_id'], ['public_id'])
    # ### end Alembic commands ###
