"""empty message

Revision ID: d9926beecff0
Revises: 647b5c08124a
Create Date: 2020-01-19 16:58:58.417425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9926beecff0'
down_revision = '647b5c08124a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('coverPhoto_filename', sa.String(length=50), nullable=False))
    op.add_column('pet', sa.Column('profPhoto_filename', sa.String(length=50), nullable=False))
    op.drop_column('pet', 'profPic_filename')
    op.add_column('user', sa.Column('coverPhoto_filename', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('profPhoto_filename', sa.String(length=50), nullable=False))
    op.drop_column('user', 'profPic_filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profPic_filename', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('user', 'profPhoto_filename')
    op.drop_column('user', 'coverPhoto_filename')
    op.add_column('pet', sa.Column('profPic_filename', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('pet', 'profPhoto_filename')
    op.drop_column('pet', 'coverPhoto_filename')
    # ### end Alembic commands ###
