"""empty message

Revision ID: dbfb4ceaeac9
Revises: c79ad0841767
Create Date: 2020-01-18 18:39:45.457270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbfb4ceaeac9'
down_revision = 'c79ad0841767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet_sale_rel', sa.Column('deal_id', sa.String(), nullable=True))
    op.drop_constraint('pet_sale_rel_trans_id_fkey', 'pet_sale_rel', type_='foreignkey')
    op.create_foreign_key(None, 'pet_sale_rel', 'deal', ['deal_id'], ['public_id'], ondelete='cascade')
    op.drop_column('pet_sale_rel', 'trans_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet_sale_rel', sa.Column('trans_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pet_sale_rel', type_='foreignkey')
    op.create_foreign_key('pet_sale_rel_trans_id_fkey', 'pet_sale_rel', 'deal', ['trans_id'], ['public_id'], ondelete='CASCADE')
    op.drop_column('pet_sale_rel', 'deal_id')
    # ### end Alembic commands ###
