"""empty message

Revision ID: e41b8a329b47
Revises: 6892016762d1
Create Date: 2020-01-19 23:18:55.766551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41b8a329b47'
down_revision = '6892016762d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pet_pet_owner_fkey', 'pet', type_='foreignkey')
    op.create_foreign_key(None, 'pet', 'user', ['pet_owner'], ['username'], ondelete='cascade')
    op.add_column('pet_sale_rel', sa.Column('user_username', sa.String(), nullable=True))
    op.drop_constraint('pet_sale_rel_user_id_fkey', 'pet_sale_rel', type_='foreignkey')
    op.create_foreign_key(None, 'pet_sale_rel', 'user', ['user_username'], ['username'], ondelete='cascade')
    op.drop_column('pet_sale_rel', 'user_id')
    op.add_column('user_business_rel', sa.Column('user_username', sa.String(), nullable=True))
    op.drop_constraint('user_business_rel_user_id_fkey', 'user_business_rel', type_='foreignkey')
    op.create_foreign_key(None, 'user_business_rel', 'user', ['user_username'], ['username'], ondelete='cascade')
    op.drop_column('user_business_rel', 'user_id')
    op.add_column('user_circle_rel', sa.Column('user_username', sa.String(), nullable=True))
    op.drop_constraint('user_circle_rel_user_id_fkey', 'user_circle_rel', type_='foreignkey')
    op.create_foreign_key(None, 'user_circle_rel', 'user', ['user_username'], ['username'], ondelete='cascade')
    op.drop_column('user_circle_rel', 'user_id')
    op.add_column('user_comment_rel', sa.Column('user_username', sa.String(), nullable=True))
    op.drop_constraint('user_comment_rel_user_id_fkey', 'user_comment_rel', type_='foreignkey')
    op.create_foreign_key(None, 'user_comment_rel', 'user', ['user_username'], ['username'], ondelete='cascade')
    op.drop_column('user_comment_rel', 'user_id')
    op.add_column('user_pet_rel', sa.Column('user_username', sa.String(), nullable=True))
    op.drop_constraint('user_pet_rel_user_id_fkey', 'user_pet_rel', type_='foreignkey')
    op.create_foreign_key(None, 'user_pet_rel', 'user', ['user_username'], ['username'], ondelete='cascade')
    op.drop_column('user_pet_rel', 'user_id')
    op.add_column('user_post_rel', sa.Column('user_username', sa.String(), nullable=True))
    op.drop_constraint('user_post_rel_user_id_fkey', 'user_post_rel', type_='foreignkey')
    op.create_foreign_key(None, 'user_post_rel', 'user', ['user_username'], ['username'], ondelete='cascade')
    op.drop_column('user_post_rel', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_post_rel', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_post_rel', type_='foreignkey')
    op.create_foreign_key('user_post_rel_user_id_fkey', 'user_post_rel', 'user', ['user_id'], ['public_id'], ondelete='CASCADE')
    op.drop_column('user_post_rel', 'user_username')
    op.add_column('user_pet_rel', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_pet_rel', type_='foreignkey')
    op.create_foreign_key('user_pet_rel_user_id_fkey', 'user_pet_rel', 'user', ['user_id'], ['public_id'], ondelete='CASCADE')
    op.drop_column('user_pet_rel', 'user_username')
    op.add_column('user_comment_rel', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_comment_rel', type_='foreignkey')
    op.create_foreign_key('user_comment_rel_user_id_fkey', 'user_comment_rel', 'user', ['user_id'], ['public_id'], ondelete='CASCADE')
    op.drop_column('user_comment_rel', 'user_username')
    op.add_column('user_circle_rel', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_circle_rel', type_='foreignkey')
    op.create_foreign_key('user_circle_rel_user_id_fkey', 'user_circle_rel', 'user', ['user_id'], ['public_id'], ondelete='CASCADE')
    op.drop_column('user_circle_rel', 'user_username')
    op.add_column('user_business_rel', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_business_rel', type_='foreignkey')
    op.create_foreign_key('user_business_rel_user_id_fkey', 'user_business_rel', 'user', ['user_id'], ['public_id'], ondelete='CASCADE')
    op.drop_column('user_business_rel', 'user_username')
    op.add_column('pet_sale_rel', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pet_sale_rel', type_='foreignkey')
    op.create_foreign_key('pet_sale_rel_user_id_fkey', 'pet_sale_rel', 'user', ['user_id'], ['public_id'], ondelete='CASCADE')
    op.drop_column('pet_sale_rel', 'user_username')
    op.drop_constraint(None, 'pet', type_='foreignkey')
    op.create_foreign_key('pet_pet_owner_fkey', 'pet', 'user', ['pet_owner'], ['public_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
